/*
* MORFEO Project
* http://www.morfeo-project.org
*
* Component: TIDNotifJ
* Programming Language: Java
*
* File: $Source$
* Version: $Revision: 3 $
* Date: $Date: 2006-01-17 17:42:13 +0100 (Tue, 17 Jan 2006) $
* Last modified by: $Author: aarranz $
*
* (C) Copyright 2005 Telefónica Investigación y Desarrollo
*     S.A.Unipersonal (Telefónica I+D)
*
* Info about members and contributors of the MORFEO project
* is available at:
*
*   http://www.morfeo-project.org/TIDNotifJ/CREDITS
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*
* If you want to use this software an plan to distribute a
* proprietary application in any way, and you are not licensing and
* distributing your source code under GPL, you probably need to
* purchase a commercial license of the product.  More info about
* licensing options is available at:
*
*   http://www.morfeo-project.org/TIDNotifJ/Licensing
*/ 

/* Generated By:JJTree: Do not edit this line. TIDBasicAnyValue.java */

package es.tid.util.parser;


public class TIDBasicAnyValue extends SimpleNode 
{
  private AnyValue anyvalue = null;

  public TIDBasicAnyValue(int id) 
  {
    super(id);
    super.node_type = NodeType.TIDBasicAnyValue;
    anyvalue = new AnyValue();
  }

  public TIDBasicAnyValue(ConstraintParser p, int id) 
  {
    super(p, id);
    super.node_type = NodeType.TIDBasicAnyValue;
    anyvalue = new AnyValue();
  }

  public org.omg.DynamicAny.DynAny value(org.omg.DynamicAny.DynAny dynAny)
  {
     return (org.omg.DynamicAny.DynAny) dynAny._duplicate();
  }

  public TypeValuePair evaluate( org.omg.DynamicAny.DynAny dynany )
  {
    if (anyvalue != null)
    { 
      org.omg.DynamicAny.DynAny chosen = anyvalue.value(dynany);
      if (chosen._non_existent())
      {
        return new TypeValuePair();
      }
      return anyvalue.evaluate(chosen);
    }
    return new TypeValuePair();
  }
}
