/*
* MORFEO Project
* http://www.morfeo-project.org
*
* Component: TIDNotifJ
* Programming Language: Java
*
* File: $Source$
* Version: $Revision: 3 $
* Date: $Date: 2006-01-17 17:42:13 +0100 (Tue, 17 Jan 2006) $
* Last modified by: $Author: aarranz $
*
* (C) Copyright 2005 Telefónica Investigación y Desarrollo
*     S.A.Unipersonal (Telefónica I+D)
*
* Info about members and contributors of the MORFEO project
* is available at:
*
*   http://www.morfeo-project.org/TIDNotifJ/CREDITS
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*
* If you want to use this software an plan to distribute a
* proprietary application in any way, and you are not licensing and
* distributing your source code under GPL, you probably need to
* purchase a commercial license of the product.  More info about
* licensing options is available at:
*
*   http://www.morfeo-project.org/TIDNotifJ/Licensing
*/ 

/* Generated By:JJTree: Do not edit this line. TIDUnaryExpr.java */

package es.tid.util.parser;

import es.tid.util.parser.Operations.TIDUnaryOperations;

public class TIDUnaryExpr extends SimpleNode implements TIDUnaryOperations, TIDConstraintMsg
{
  private static final String NODENAME = "UnaryExpr: ";

  private String name;
  private int operator;

  public TIDUnaryExpr(int id) {
    super(id);
    super.node_type = NodeType.TIDUnaryExpr;
  }

  public TIDUnaryExpr(ConstraintParser p, int id) {
    super(p, id);
    super.node_type = NodeType.TIDUnaryExpr;
  }

/*
  public void setName(String n) 
  {
    if (n.toUpperCase().compareTo(NOT_OP_STR) == 0)
    {
      operator = NOT_OP;
      name = NOT_OP_STR;
    }
    else if (n.toUpperCase().compareTo(EXIST_OP_STR) == 0)
    {
      operator = EXIST_OP;
      name = EXIST_OP_STR;
    }
  }
*/

  public void setOp(int n) 
  {
    try
    {
      operator = n;
      name = STR_OP[n-FIRST_OP];
    }
    catch (Exception e)
    {
      operator = UNKNOWN_OP;
      name = STR_OP[UNKNOWN_OP-FIRST_OP];
    }
  }

  public int getOp()
  {
    return this.operator;
  }

  public String toString() {
    return NODENAME + name;
  }

  public TypeValuePair evaluate( org.omg.DynamicAny.DynAny dynany )
  {
    TypeValuePair result = new TypeValuePair();

    if (children != null) 
    {
      for (int i = 0; i < children.length; ++i) 
      {
        SimpleNode n = (SimpleNode)children[i];

        if (n != null) 
        {
          result = n.evaluate( dynany );
          break;
        }
      }

      switch (operator)
      {
        case NOT_OP:
          switch (result.type)
          {
            case TypeValuePair.BOOLTYPE:
              result.val.objVal =
                   new Boolean(!(((Boolean)result.val.objVal).booleanValue()));
              break;
            //case TypeValuePair.ERRTYPE:
            //  result.type = TypeValuePair.ERRTYPE;
            default:
              TIDParser.print(TIDParser.DEBUG, TUE_DEFAULT);
          }
          break;
        case EXIST_OP:
          // not implemented at the moment: return always ERRTYPE
          //result = new TypeValuePair(false);
          break;
      }
    }
    return result;
  }
}
