///////////////////////////////////////////////////////////////////////////
//
// File          : TIDDistribAdmin.idl
// Description   : 
//                 
// Author/s      : Alvaro Rodriguez
// Project       : 
// Rel           : 01.00
// Created       : 22/11/00
// Revision Date : 22/11/00 
// Rev. History  : 
//
// Copyright 2000 Telefonica, I+D. All Rights Reserved.
//
// The copyright of the software program(s) is property of Telefonica.
// The program(s) may be used, modified and/or copied only with the 
// express written consent of Telefonica or in acordance with the terms 
// and conditions stipulated in the agreement/contract under which 
// the program(s) have been supplied.
//
///////////////////////////////////////////////////////////////////////////


#ifndef _TIDDistribAdmin_idl_
#define _TIDDistribAdmin_idl_

//#include "NotificationService.idl"
#include "DistributionChannelAdmin.idl"

#pragma prefix "corba.tid.es"

module TIDDistribAdmin
{
  enum ServiceState { cannot_run, can_run, running, shutdowned };

  struct ServiceStatus {
    ServiceState state;
    string msgs;
  };

  enum TraceLevel { none, error, user, debug, deep_debug };

  interface Agent
  {
    exception CannotProceed
    {
      string why;
    };

    //void start () raises (CannotProceed);

    //void stop () raises (CannotProceed);

    //void resume () raises (CannotProceed);

    void trace_on (in TraceLevel trace_level) raises (CannotProceed);

    void trace_off () raises (CannotProceed);


    DistributionChannelAdmin::DistributionChannelFactory channel_factory ()
                                                        raises (CannotProceed);

    DistributionChannelAdmin::DistributionChannelSeq list_channels ()
                                                        raises (CannotProceed);

    // Metodo que deben de tener todos los Admin's para finalizar el servicio
    void shutdown_service () raises (CannotProceed);
    void shutdown () raises (CannotProceed);
  };
};

#endif // _TIDDistribAdmin_idl_
